#!/bin/bash
NAMESPACE_ID="a04e3f82aa4c4f0c92551599b30ac018"

# CVS
npx wrangler kv:key put "jobs:cvs" '[{"id":"cvs_001","title":"CU 편의점 야간 알바 모집","company":"CU 강남역점","location":"서울 강남구 강남역","salary":"시급 12,000원 (야간 1.5배)","description":"야간 시간대 근무할 성실한 직원을 모집합니다.","requirements":"• 성실하고 책임감\n• 야간 근무 가능\n• 장기 근무 우대","url":"https://www.alba.co.kr","source":"알바몬","keywords":["편의점","CU","야간"],"category":"cvs"},{"id":"cvs_002","title":"GS25 주간 아르바이트","company":"GS25 역삼점","location":"서울 강남구 역삼동","salary":"시급 10,000원","description":"주간 시간대 근무할 밝고 성실한 직원 모집.","requirements":"• 밝고 친절\n• 주 3일 이상","url":"https://www.saramin.co.kr","source":"사람인","keywords":["편의점","GS25"],"category":"cvs"},{"id":"cvs_003","title":"세븐일레븐 오픈/마감","company":"세븐일레븐 서초점","location":"서울 서초구","salary":"시급 10,500원","description":"오픈 또는 마감 시간대 근무 가능한 직원 모집.","requirements":"• 장기 근무 가능\n• 성실한 태도","url":"https://www.jobkorea.co.kr","source":"잡코리아","keywords":["편의점","세븐일레븐"],"category":"cvs"}]' --namespace-id $NAMESPACE_ID

# Restaurant
npx wrangler kv:key put "jobs:restaurant" '[{"id":"restaurant_001","title":"외식업체 홀서빙","company":"아웃백 스테이크하우스","location":"서울 강남구","salary":"시급 11,000원 + 팁","description":"고급 레스토랑 홀서빙 직원 모집.","requirements":"• 친절하고 적극적\n• 주 4일 이상","url":"https://www.saramin.co.kr","source":"사람인","keywords":["레스토랑","서빙"],"category":"restaurant"},{"id":"restaurant_002","title":"한식당 주방보조","company":"한일관 본점","location":"서울 중구","salary":"월급 250만원","description":"전통 한식당 주방보조. 식사 및 기숙사 제공.","requirements":"• 체력이 좋은 분\n• 위생관념","url":"https://www.alba.co.kr","source":"알바몬","keywords":["한식당","주방"],"category":"restaurant"},{"id":"restaurant_003","title":"레스토랑 홀매니저","company":"빕스 강남점","location":"서울 강남구","salary":"월급 280만원","description":"매장 운영 및 직원 관리 담당.","requirements":"• 외식업 경력 1년 이상\n• 리더십","url":"https://www.jobkorea.co.kr","source":"잡코리아","keywords":["레스토랑","매니저"],"category":"restaurant"}]' --namespace-id $NAMESPACE_ID

# Retail
npx wrangler kv:key put "jobs:retail" '[{"id":"retail_001","title":"의류매장 판매사원","company":"유니클로 강남점","location":"서울 강남구","salary":"시급 10,500원","description":"의류 판매 및 매장 관리 담당.","requirements":"• 패션 관심\n• 주 5일 근무","url":"https://www.saramin.co.kr","source":"사람인","keywords":["매장","판매","의류"],"category":"retail"},{"id":"retail_002","title":"화장품 매장 뷰티어드바이저","company":"올리브영 역삼점","location":"서울 강남구 역삼동","salary":"시급 11,000원 + 인센티브","description":"고객 상담 및 제품 판매.","requirements":"• 뷰티 관심\n• 밝고 친절","url":"https://www.alba.co.kr","source":"알바몬","keywords":["화장품","뷰티"],"category":"retail"},{"id":"retail_003","title":"편집샵 매장관리","company":"ABC마트 강남점","location":"서울 강남구","salary":"월급 240만원","description":"신발/패션 제품 판매 및 재고 관리.","requirements":"• 판매 경험 1년 이상\n• 재고 관리","url":"https://www.jobkorea.co.kr","source":"잡코리아","keywords":["매장관리","판매"],"category":"retail"}]' --namespace-id $NAMESPACE_ID

# Fastfood
npx wrangler kv:key put "jobs:fastfood" '[{"id":"fastfood_001","title":"맥도날드 크루 모집","company":"맥도날드 강남역점","location":"서울 강남구 강남역","salary":"시급 10,500원","description":"고객 주문 접수, 조리, 서빙 담당.","requirements":"• 밝고 친절\n• 주 3일 이상","url":"https://www.saramin.co.kr","source":"사람인","keywords":["패스트푸드","맥도날드"],"category":"fastfood"},{"id":"fastfood_002","title":"버거킹 주방 조리","company":"버거킹 역삼점","location":"서울 강남구 역삼동","salary":"시급 11,000원","description":"버거 조리 및 주방 업무.","requirements":"• 빠른 업무 처리\n• 주 4일 이상","url":"https://www.alba.co.kr","source":"알바몬","keywords":["패스트푸드","버거킹"],"category":"fastfood"},{"id":"fastfood_003","title":"KFC 매장관리 사원","company":"KFC 서초점","location":"서울 서초구","salary":"월급 260만원","description":"매장 운영 및 직원 관리.","requirements":"• 외식업 경력 6개월 이상\n• 리더십","url":"https://www.jobkorea.co.kr","source":"잡코리아","keywords":["패스트푸드","KFC"],"category":"fastfood"}]' --namespace-id $NAMESPACE_ID

echo "✅ 모든 KV 데이터 업로드 완료!"
